blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^blog_app/', include('blog_app.urls', namespace="blog_app")),
    url(r'^admin/', include(admin.site.urls)),
]

blog_app/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<post_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

blog_app/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.


class Post(models.Model):
    post_title = models.CharField(max_length=100, verbose_name='Заголовок новости')
    post_text = models.CharField(max_length=500, verbose_name='Текст новости')
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.post_title

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Comment(models.Model):
    post = models.ForeignKey(Post)
    comment_text = models.CharField(max_length=256)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.comment_text

blog_app/views.py
from django.contrib.auth.decorators import *
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect

from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.views import generic

from .models import Post, Comment


class IndexView(generic.ListView):
    template_name = 'blog_app/index.html'
    context_object_name = 'latest_post_list'

    def get_queryset(self):
        """Return the last five published posts."""
        return Post.objects.filter(pub_date__lte=timezone.now).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Post
    template_name = 'blog_app/detail.html'

    def get_queryset(self):
        return Post.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Post
    template_name = 'blog_app/results.html'


def vote(request, post_id):
    p = get_object_or_404(Post, pk=post_id)
    try:
        selected_comment = p.comment_set.get(pk=request.POST['comment'])
    except (KeyError, Comment.DoesNotExist):
        # Redisplay the post voting form.
        return render(request, 'blog_app/detail.html', {
            'post': p,
            'error_message': "You didn't select a comment.",
        })
    else:
        selected_comment.votes += 1
        selected_comment.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('blog_app:results', args=(p.id,)))

blog_app/templates/blog_app/detail.html
{% extends "blog_app/template.html" %}
{% block content %}
    <h1>{{ post.post_text }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'blog_app:vote' post.id %}" method="post">
        {% csrf_token %}
        {% for comment in post.comment_set.all %}
            <input type="radio" name="comment" id="comment{{ forloop.counter }}" value="{{ comment.id }}"/>
            <label for="comment{{ forloop.counter }}">{{ comment.comment_text }}</label><br/>
        {% endfor %}
        <input type="submit" value="Vote"/>
    </form>
{% endblock %}

blog_app/templates/blog_app/index.html
{% extends "blog_app/template.html" %}

{% block content %}
    {% if latest_post_list %}
        <ul>
            {% for post in latest_post_list %}
                <li><a href="{% url 'blog_app:detail' post.id %}">{{ post.post_text }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No posts are available.</p>
    {% endif %}
{% endblock %}

blog_app/templates/blog_app/results.html
{% extends "blog_app/template.html" %}
{% block content %}
    <h1>{{ post.post_text }}</h1>

    <ul>
        {% for comment in post.comment_set.all %}
            <li>{{ comment.comment_text }} -- {{ comment.votes }} vote{{ comment.votes|pluralize }}</li>
        {% endfor %}
    </ul>

    <a href="{% url 'blog_app:detail' post.id %}">Vote again?</a>
{% endblock %}

blog_app/templates/blog_app/template.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    {% load staticfiles %}
    {% block head %}
        <link rel="stylesheet" type="text/css" href="{% static 'blog_app/style.css' %}"/>
    {% endblock %}
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>